import "./globals.css";
import "./build.css";

export const metadata = {
  title: "Rayhan Ferdous",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-slate-900 !overflow-x-hidden">{children}</body>
    </html>
  );
}
