import Container from "@/components/Layout/Container";
import GapContainer from "@/components/Layout/GapContainer";
import Header from "@/components/Layout/Header";
import Experiance from "@/components/Layout/Index/Experiance";
import FeatureProject from "@/components/Layout/Index/FeatureProject";
import Footer from "@/components/Layout/Index/Footer";
import Hero from "@/components/Layout/Index/Hero";
import ProjectShowcase from "@/components/Layout/Index/ProjectShowcase";
import Rectangle from "@/components/Layout/Rectangle";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="h-screen">
        <div className="relative overflow-hidden">
          <Rectangle className={"-top-[10%] -left-[15%]"} />
          <Container>
            <Header />
            <Hero />
            <GapContainer>
              <FeatureProject />
              <FeatureProject flipCard={"true"} />
              <ProjectShowcase />
              <Experiance />
              <Footer />
            </GapContainer>
          </Container>
        </div>
      </div>
    </>
  );
}
